spring:
  mail:
    host: smtp.163.com
    username: wang_mvvm@163.com
    password: NVRUOVOYJZXGPWPU
  datasource:
    url: jdbc:mysql://localhost:3306/book_manage
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test
    password: 123456
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
springfox:
  documentation:
    enabled: false